let words=[
	"binary image",
	"Kernel",
	"RGBimage",
	"HSVimage",
	"DomainNameSystem",
	"LocalAreaNetwork",
	"Sustainable Development Goals",
	//"International Organization for Standardization",
	"Virtual Private Network",
	"Central Processing Unit",
	"Nash equilibrium",
	"Synchronicity",
	"Hypertext Transfer Protocol",
	"deoxyribonucleicacid",
	"ascorbicacid",
	"Flip Flop",
	"Storage Area Network",
	"Network Attached Storage",
	"World Wide Web",
	"Python",
  ];
